### ISSUE TITLE
[windows ] ContainerService.WaitForProcess throws index out of bounds exception

### ISSUE THREAD

**Issue by ta32** [mariotoffia/FluentDocker#111]
Hi 

I am using a windows container, when the following line executes
Ductus.FluentDocker 2.7.2
ContainerService = new Builder().UseContainer();
...
.Build()
.Start();
ContainerService.WaitForProcess( "ServiceMonitor.exe", 30000 );

Here is the stack trace

```cmd
cmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine inspect 0174d750b9870ebbc9e35100085298edeb0f1e08014ffda0edf79bf8cbe1b316cmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine top 0174d750b9870ebbc9e35100085298edeb0f1e08014ffda0edf79bf8cbe1b316W, 25436, 15, 2019/09/23, 16:51:38.140, HOSTNAME\QTAgent.exe, AgentProcess:CurrentDomain_UnhandledException: Entered
E, 25436, 15, 2019/09/23, 16:51:38.144, HOSTNAME\QTAgent.exe, AgentProcess:CurrentDomain_UnhandledException: IsTerminating : System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ductus.FluentDocker.Executors.Parsers.ClientTopResponseParser.ColumnSplit(IList`1 columns, String row)
   at Ductus.FluentDocker.Executors.Parsers.ClientTopResponseParser.Process(ProcessExecutionResult response)
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Services.Extensions.ContainerExtensions.GetRunningProcesses(IContainerService service)
   at Ductus.FluentDocker.Services.Extensions.ContainerExtensions.<>c__DisplayClass9_1.<WaitForProcess>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Index and length must refer to a location within the string.
```

**Comment by mariotoffia** [comment]
`Thanks for the bug report! Could you please provide with a More complete test stup so I can reproduce and fix it.

Cheers,
 Mario`

**Comment by ta32** [comment]
Hi i created a simple windows container. You need windows 10 to run this container.
I am running docker desktop 2.1.0.1
```
FROM microsoft/windowsservercore:1607
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
RUN choco feature enable --name=allowGlobalConfirmation
RUN choco install python3
COPY "server.py" "C:/"
EXPOSE 8000
CMD ["python", "server.py"]
```
```
import http.server
import socketserver
PORT = 8000
Handler = http.server.SimpleHTTPRequestHandler
with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("serving at port", PORT)
    httpd.serve_forever()
```
i built this container and called it test. Make sure the container not running, then run the bellow code. 

the following code threw an exception ( i was debugging and stepped over it ) 
```
            ContainerService = new Builder().UseContainer()
            .UseImage( "test" )
            .ExposePort( 8000, 8000 )
            .Build()
            .Start()
            .WaitForProcess( "python.exe", 30000 );
```

here is the stack trace 
```
cmd: C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe - arg: ls --format="{{.Name}};{{.State}};{{.URL}}"cmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine ps --quiet --no-trunccmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine create  -p 8000:8000 testcmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine inspect c8171387c9c16dd02623000daf3ba24cd96c128b4cc8ab46db3f1666e4f7ea67cmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine start c8171387c9c16dd02623000daf3ba24cd96c128b4cc8ab46db3f1666e4f7ea67The thread 0x5d40 has exited with code 0 (0x0).
The thread 0x5f74 has exited with code 0 (0x0).
The thread 0x2410 has exited with code 0 (0x0).
The thread 0x7b78 has exited with code 0 (0x0).
The thread 0x7e20 has exited with code 0 (0x0).
The thread 0x59ec has exited with code 0 (0x0).
cmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine inspect c8171387c9c16dd02623000daf3ba24cd96c128b4cc8ab46db3f1666e4f7ea67cmd: C:\Program Files\Docker\Docker\Resources\bin\docker.exe - arg:  -H npipe:////./pipe/docker_engine top c8171387c9c16dd02623000daf3ba24cd96c128b4cc8ab46db3f1666e4f7ea67W, 32404, 14, 2019/09/23, 18:16:17.908, DEV-THIVANKA\QTAgent.exe, AgentProcess:CurrentDomain_UnhandledException: Entered
E, 32404, 14, 2019/09/23, 18:16:17.913, DEV-THIVANKA\QTAgent.exe, AgentProcess:CurrentDomain_UnhandledException: IsTerminating : System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Ductus.FluentDocker.Executors.Parsers.ClientTopResponseParser.ColumnSplit(IList`1 columns, String row)
   at Ductus.FluentDocker.Executors.Parsers.ClientTopResponseParser.Process(ProcessExecutionResult response)
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Services.Extensions.ContainerExtensions.GetRunningProcesses(IContainerService service)
   at Ductus.FluentDocker.Services.Extensions.ContainerExtensions.<>c__DisplayClass9_1.<WaitForProcess>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Index and length must refer to a location within the string.
```

**Comment by mariotoffia** [comment]
@ta32 The ```WaitForProcess``` now works correctly on windows container as well as Unix containers. Sorry for the delay but I needed to upgrade the ```DockerFileBuilder``` and some other bits and pieces in order to get a ok unit test.

Now the following works.
```cs
 using (var scope = Fd.EngineScope(EngineScopeType.Windows))
      {
        using (
          var container =
            Fd.DefineImage("mariotoffia/issue111").ReuseIfAlreadyExists()
              .From("mcr.microsoft.com/windows/servercore:ltsc2019")
              .Shell("powershell", "-Command", "$ErrorActionPreference = 'Stop';")
              .Run("Set-ExecutionPolicy Bypass -Scope Process -Force; " +
                   "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12")
              .Run("Invoke-WebRequest -OutFile install.ps1 https://www.chocolatey.org/install.ps1; " +
                   "./install.ps1")
              .Run("choco feature enable --name=allowGlobalConfirmation")
              .Run("choco install python3")
              .Copy("Resources/Issue/111/server.py", "C:/")
              .ExposePorts(8000)
              .Command("python", "server.py")
              .Builder().UseContainer().UseImage("mariotoffia/issue111")
              .WaitForProcess("python.exe", (long) TimeSpan.FromSeconds(30).TotalMilliseconds)
              .Builder()
              .Build()
              .Start())
        {
          var c = container.Containers.First();
          var config = c.GetConfiguration(true);
          AreEqual(ServiceRunningState.Running, config.State.ToServiceState());
        }
      }
```

This will be included in the next release.

Cheers,
 Mario
