### ISSUE TITLE
wait for healthy expires immediately when called on IContainerService

### ISSUE THREAD

**Issue by jetersen** [mariotoffia/FluentDocker#140]
Seems like a logic bug that makes it immediately expire.
```
Ductus.FluentDocker.Common.FluentDockerException: Wait for healthy expired for container 539967b2ca8f5ab4bda51916591755e3569441e1408c8dcd823b8106bbf35ea7
   at Ductus.FluentDocker.Services.Extensions.ContainerExtensions.WaitForHealthy(IContainerService service, Int64 millisTimeout)
   at GitLabApiClient.Test.Utilities.GitLabContainerFixture.StartContainer() in C:\git\code\GitLabApiClient\test\GitLabApiClient.Test\Utilities\GitLabContainerFixture.cs:line 48
   at GitLabApiClient.Test.Utilities.GitLabContainerFixture.InitializeAsync() in C:\git\code\GitLabApiClient\test\GitLabApiClient.Test\Utilities\GitLabContainerFixture.cs:line 26
```

```csharp
            var compositeService = new Builder()
                .UseContainer()
                .UseCompose()
                .FromFile($"{ProjectRootFolder}/docker/docker-compose.yml")
                .Build()
                .Start();

            _gitlabContainer = compositeService.Containers.FirstOrDefault();
            _gitlabContainer.WaitForHealthy();
```

**Comment by casz** [comment]
I need to use docker-compose cause I want to do multi line env which is not supported by `WithEnvironment` on docker container.

```csharp
            _gitlabContainer = new Builder()
                .UseContainer()
                .UseImage(_gitlabDockerImage)
                .WithEnvironment(
                    "GITLAB_ROOT_PASSWORD=passsword",
                    "GITLAB_OMNIBUS_CONFIG=prometheus['enable'] = false; prometheus_monitoring['enable'] = false; alertmanager['enable'] = false; grafana['enable'] = false;"
                 )
                 .WaitForHealthy()
                 .Build()
                 .Start();
                
```

**Comment by casz** [comment]
Seems like `WaitForHealthy` only works on `ContainerBuilder` and not `IContainerService`

**Comment by casz** [comment]
I ended up solving my problem

```
        private const string InitRb = "/tmp/init.rb";
        private const string GitlabRb = "/tmp/gitlab.rb";
        private static readonly TemplateString SolutionRootFolder = "${PWD}/../../../../..";

        private IContainerService _gitlabContainer;
        private readonly string _gitlabDockerImage = "gitlab/gitlab-ce:12.5.4-ce.0";

...

            _gitlabContainer = new Builder()
                .UseContainer()
                .UseImage(_gitlabDockerImage)
                .WithEnvironment(
                    "GITLAB_ROOT_PASSWORD=passsword",
                    $"GITLAB_OMNIBUS_CONFIG=from_file('{GitlabRb}')"
                )
                .CopyOnStart($"{SolutionRootFolder}/docker/gitlab.rb", GitlabRb)
                .CopyOnStart($"{SolutionRootFolder}/docker/init.rb", InitRb)
                .WaitForHealthy()
                .Build()
                .Start();
```

**Comment by mariotoffia** [comment]
Thanks @casz ! :)

**Comment by mariotoffia** [comment]
Neither me or you have done anything on this - I need to prioritize other parts on this library so I close this for now.
