### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JanEggers** [mariotoffia/FluentDocker#165]
System.NullReferenceException: Object reference not set to an instance of an object.
at Ductus.FluentDocker.Extensions.CommandExtensions.ResolveBinary(String dockerCommand, Boolean preferMachine, Boolean forceResolve)
at Ductus.FluentDocker.Commands.Compose.ComposeUp(DockerUri host, String altProjectName, Boolean forceRecreate, Boolean noRecreate, Boolean dontBuild, Boolean buildBeforeCreate, Nullable`1 timeout, Boolean removeOphans, Boolean useColor, String[] services, ICertificatePaths certificates, String[] composeFile)
at Ductus.FluentDocker.Services.Impl.DockerComposeCompositeService.Start()
at Ductus.FluentDocker.Services.Impl.DockerComposeCompositeService.Ductus.FluentDocker.Services.ICompositeService.Start()

locally the lib is working fine on the buildserver we get a nullpointer exception

**Comment by mariotoffia** [comment]
It seems that you don't have docker-compose on the path on the build server - could that be the case?

**Comment by JanEggers** [comment]
@mariotoffia I just verified. docker-compose was not even installed. the buildsystem runs on server os and the docker installation did not contain the compose binaries.

I know that is it was my fault but can you please update your library anyway so the error is a little more helpful?
