### ISSUE TITLE
How to connect to mongodb using FluentDocker?

### ISSUE THREAD

**Issue by jolienai** [mariotoffia/FluentDocker#223]
I am trying to use FluentDocker to run the tests against MongoDB, but I cannot connect to it, see the code below.

```cs
            [Fact]
            public async Task TestMongoDbConnection3()
            {
                const string root = "root";
                const string secret = "secret";
                
                using (
                    var container =
                        new Builder().UseContainer()
                            .UseImage("mongo")
                            .WithEnvironment($"MONGO_INITDB_ROOT_USERNAME:{root}")
                            .WithEnvironment($"MONGO_INITDB_ROOT_PASSWORD:{secret}")
                            .ExposePort(27018)
                            .WaitForPort("27018/tcp", 30000 /*30s*/)
                        .Build()
                        .Start())
            {
                var config = container.GetConfiguration(true);
                Assert.Equal(ServiceRunningState.Running, config.State.ToServiceState());
                
                const string connectionString = "mongodb://root:secret@localhost:27018";

                // insert data 
                const string collectionName = "Users";
                
                var mongoClient = new MongoClient(connectionString);
                var database = mongoClient.GetDatabase ("Users");
                var collection = database.GetCollection<User>(collectionName);
                
                const int id = 1;
                var data = new Fixture().Build<User>()
                    .With(x => x.Id, id)
                    .Create();

                // delete if exists, but got timeout after 30000 ms
                await collection.DeleteOneAsync(x => x.AccountId == data.AccountId);
                
                ...
            }
        }
```

I tried to replace the localhost for the IP from config (config.NetworkSettings.IPAddress), but still getting the timeout.

Any idea?

Many thanks,

**Comment by jolienai** [comment]
Hi Mario, thank you a lot for replying.

I am still having issues connecting to the database, I made the changes you said, but now I am getting "Unable to authenticated using sasl protocol mechanism SCRAM-SHA-1"

I had this issue before when I was not using FluentDocker, and I solve it by add "/DatabaseName?authSource=admin&readPreference=primary&ssl=false" but it still not working.

Regarding the 27018 port, I am trying to use, even the default port is 27017 you can set another port in the docker compose file as below.

```
# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
     ports:
       - 27018:27017
```

**Comment by jolienai** [comment]
HI @mariotoffia the env variables set was wrong, so I manage to fix it, now the connection is working locally. However, it is failing when the test is running inside a docker-in-docker image in the CI pipeline.

Here is the test I am trying to do

```
[Fact]
public void Test_Run_PingCommand_returns_True()
{
    const string root = "root";
    const string secret = "secret";

    using (
        var container =
            new Builder().UseContainer()
                .UseImage("mongo")
                .WithEnvironment(new []{$"MONGO_INITDB_ROOT_USERNAME={root}",
                    $"MONGO_INITDB_ROOT_PASSWORD={secret}"})
                .ExposePort(27017)
                .WaitForPort("27017/tcp", 30000 /*30s*/)
                .Build()
                .Start())
    {
        var config = container.GetConfiguration(true);
        Assert.Equal(ServiceRunningState.Running, config.State.ToServiceState());
       
        var ep = container.ToHostExposedEndpoint("27017/tcp");
       
        var connectionString =
            $"mongodb://{root}:{secret}@{ep}";
       
        var setting = new UsageDbSettings();
        var mongoClient = new MongoClient(connectionString);
        var database = mongoClient.GetDatabase(setting.DatabaseName);
        
        var isMongoLive = database.RunCommandAsync((Command<BsonDocument>)"{ping:1}").Wait(30000);
       
        Assert.True(isMongoLive);
    }
}
```

Now I am getting timeout

```
[xUnit.net 00:00:53.76] Cost.Infrastructure.Tests.DataSources.Mongodb.MongoDbConnectionTests.Test_Run_PingCommand_returns_True [FAIL]
61 X Cost.Infrastructure.Tests.DataSources.Mongodb.MongoDbConnectionTests.Test_Run_PingCommand_returns_True [52s 539ms]
62 Error Message:
63 Ductus.FluentDocker.Common.FluentDockerException : Timeout waiting for service at = 0.0.0.0 port = 38926
64---- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 0.0.0.0:38926
65 Stack Trace:
66 at Ductus.FluentDocker.Services.Extensions.NetworkExtensions.WaitForPort(IPEndPoint endpoint, Int64 millisTimeout)
67 at Ductus.FluentDocker.Services.Extensions.NetworkExtensions.WaitForPort(IContainerService service, String portAndProto, Int64 millisTimeout, String address)
68 at Ductus.FluentDocker.Builders.ContainerBuilder.<>c__DisplayClass73_1.<AddHooks>b__12(IService svc)
69 at Ductus.FluentDocker.Fd.DisposeOnException[T](Action`1 action, T service, String name)
70 at Ductus.FluentDocker.Builders.ContainerBuilder.<AddHooks>b__73_1(IService service)
71 at Ductus.FluentDocker.Services.Impl.ServiceHooks.Execute(IService service, ServiceRunningState state)
72 at Ductus.FluentDocker.Services.Impl.DockerContainerService.set_State(ServiceRunningState value)
73 at Ductus.FluentDocker.Services.Impl.DockerContainerService.Ductus.FluentDocker.Services.IService.Start()
74 at Ductus.FluentDocker.Services.Impl.DockerContainerService.Start()
75 at Cost.Infrastructure.Tests.DataSources.Mongodb.MongoDbConnectionTests.Test_Run_PingCommand_returns_True() in /builds/billing/cost/Cost.Infrastructure.Tests/DataSources/Mongodb/MongoDbConnectionTests.cs:line 112

76----- Inner Stack Trace -----
77 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
78 at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
79 at Ductus.FluentDocker.Services.Extensions.NetworkExtensions.WaitForPort(IPEndPoint endpoint, Int64 millisTimeout)
80Test Run Failed.
81Total tests: 1
82 Failed: 1
83 Total time: 54.7567 Seconds
```

**Comment by jolienai** [comment]
Hi @mariotoffia, I am still having the timeout issue.  The idea is to use FluentDocker to use to test the MongoDB repositories so that I can insert some data, call the repo and validate the data it is returned. 

I am using GitLab, so in the build step I am using the dind image from the docker file similar to this:

```
FROM mcr.microsoft.com/dotnet/sdk:3.1
COPY nuget.config /root/.nuget/NuGet/NuGet.Config

ENV nuget_api_key XXXXXXXXXXXXXXXXXXXXXX

# Install Docker from Docker Inc. repositories.
RUN curl -sSL https://get.docker.com/ | sh && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y docker-ce && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

 # Install docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
RUN /usr/local/bin/docker-compose --version

# Install the magic wrapper.
ADD ./wrapdocker /usr/local/bin/wrapdocker
RUN chmod +x /usr/local/bin/wrapdocker

# Define additional metadata for our image.
VOLUME /var/lib/docker
EXPOSE 2375
ENV LOG=file
ENTRYPOINT ["wrapdocker"]
CMD []
```

**Comment by mariotoffia** [comment]
@jolienai  have you tried [this](https://stackoverflow.com/questions/62269708/gitlab-ci-docker-container-cannot-connect-to-mongodb-service). Seems to have the same problem as you on GitLab.

Cheers,
 Mario :)
