### ISSUE TITLE
StreamProcessExecutor fails if SudoMechanism Password is set

### ISSUE THREAD

**Issue by bradapeterson** [mariotoffia/FluentDocker#241]
# Issue
StreamProcessExecutor fails if SudoMechanism Password is set.

## Exception
```
System.ComponentModel.Win32Exception
An error occurred trying to start process 'echo ******** | sudo -S /usr/bin/docker' with working directory '/mnt/data/dev/fluentdocker.demo/bin/Debug/net6.0'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ductus.FluentDocker.Executors.ConsoleStream`1..ctor(ProcessStartInfo startInfo, IStreamMapper`1 mapper, CancellationToken token)
   at Ductus.FluentDocker.Executors.StreamProcessExecutor`2.Execute(CancellationToken token)
```

# Potential Cause
The ConsoleStream's constructor on line 60 is trying to start a process with a FileName of "echo somepassword | sudo -S /usr/bin/docker... " and no arguments.
[Source: https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/ConsoleStream.cs#L60](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/ConsoleStream.cs#L60)

The StreamProcessorExecutor does not seem to take the SudoMechanism Password into account, unlike the ProcessExecutor.

The StreamProcessExecutor's constructor:
```cs
public StreamProcessExecutor(string command, string arguments, string workingdir = null)
{
    _command = command;
    _arguments = arguments;
    _workingdir = workingdir;
}
```
[Source: https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/StreamProcessExecutor.cs](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/StreamProcessExecutor.cs#L14-L19)

The ProcessExecutor does not seem to have this issue.

The ProcessExecutor's constructor:
```cs
public ProcessExecutor(string command, string arguments, string workingdir = null)
{
    _workingdir = workingdir;
    if (command.StartsWith("echo") || command.StartsWith("sudo"))
    {
    _command = CommandExtensions.DefaultShell;
    _arguments = $"-c \"{command} {arguments}\"";

    return;
    }

    _command = command;
    _arguments = arguments;
}
```
[Source: https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/ProcessExecutor.cs](https://github.com/mariotoffia/FluentDocker/blob/master/Ductus.FluentDocker/Executors/ProcessExecutor.cs#L16-L29)

**Comment by mariotoffia** [comment]
Thanks, @bradapeterson  for your very well reported bug! I've added it to my `TODO` list.

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
**Resolved in v3.0.0.** The v3 ground-up rewrite implements (or fixes) what this issue asked for.

The v2 bug was an asymmetry between two now-deleted classes: ProcessExecutor wrapped "echo pw | sudo -S ..." in a shell (/bin/sh -c), but StreamProcessExecutor passed the whole composite string as ProcessStartInfo.FileName, causing Win32Exception "No such file or directory". v3 is a ground-up rewrite that deleted the entire Ductus.FluentDocker.Executors namespace (StreamProcessExecutor, ConsoleStream, ProcessExecutor) — grep finds zero references in the v3 source tree. Both the non-streaming and streaming execution paths now funnel through ONE shared helper BuildSudoCommand, eliminating the discrepancy. That helper sets FileName="sudo" (a real executable) with "-S {binary} {args}" and writes the password to stdin via process.StandardInput.WriteLineAsync — never as part of FileName and never on the command line. This removes the root cause for streaming exactly as for non-streaming.

<sub>Where this lives in v3: v3 unified sudo handling: FluentDocker/Drivers/Docker/Cli/DockerCliDriverBase.cs — BuildSudoCommand (lines 414-423) returns ("sudo", "-S {binaryPath} {arguments}", sudoPassword) for SudoMechanism.Password; consumed identically by the non-streaming ExecuteProcessAsync (lines 179-270, password written via StandardInput.WriteLineAsync at line 224) and the streaming ExecuteStreamingCommandAsync (lines 278-328, FileName=processFileName at 291, RedirectStandardInput=passwordForStdin!=null at 295, password written at line 307). Identical pattern in FluentDocker/Drivers/Podman/Cli/PodmanCliDriverBase.cs (BuildSudoCommand at line 359-365, streaming path lines 228-259). Binary carries the password…</sub>

Closing as part of the v3 issue sweep. If your scenario still isn't covered by v3, please reopen with a v3 reproduction and we'll take another look. Thanks for the report! 🙏
