### ISSUE TITLE
Could not dispose composite service 

### ISSUE THREAD

**Issue by codechrysalis-doug** [mariotoffia/FluentDocker#269]
```
2022-08-09 17:20:50[08:20:50 ERR] Top Level Exception occured. Trying to soldier on! Could not dispose composite service from file(s) /app/images/node-git-karma/docker-compose.yaml
2022-08-09 17:20:50 Ductus.FluentDocker.Common.FluentDockerException: Could not dispose composite service from file(s) /app/images/node-git-karma/docker-compose.yaml
2022-08-09 17:20:50 at Ductus.FluentDocker.Services.Impl.DockerComposeCompositeService.Dispose()
2022-08-09 17:20:50 at Ductus.FluentDocker.Fd.Run[T](Func`2 builder, Action`1 run, String name)
2022-08-09 17:20:50 at Ductus.FluentDocker.Fd.Composite(Func`2 builder, Action`1 run, String name)
```

**Comment by mariotoffia** [comment]
Hi @codechrysalis-doug. Can you, please, check your console (if you enable **logging**) what `docker` commands being executed during dispose? If you run those manually what is the output?

**Comment by codechrysalis-doug** [comment]
> Hi @codechrysalis-doug. Can you, please, check your console (if you enable **logging**) what `docker` commands being executed during dispose? If you run those manually what is the output?

Hey, thank you for getting back to me! I checked the https://github.com/mariotoffia/FluentDocker#logging and wasn't sure which file that configuration belonged to. Could you explain to me how I can set the logs? I have no experience with C# and it's ecosystems, my apologies. 

I did find in the code base there was a logger set, but the logs didn't give the granularity that you mentioned.
```
    private static void ConfigureLogging()
    {
      Log.Logger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        .WriteTo.Console()
        .CreateLogger();
    }
  ```

**Comment by codechrysalis-doug** [comment]
> Hi @codechrysalis-doug. Can you, please, check your console (if you enable **logging**) what `docker` commands being executed during dispose? If you run those manually what is the output?

Follow-up: I tried to enable logging and a few other things and I wasn't able to get the FluentDocker to give me the logs even with log level debug. It does show me the error, but that's it. Do you have an example project for how I can get the logs from FluentDocker running the container?

**Comment by mariotoffia** [comment]
Hi @codechrysalis-doug sorry for late reply. Can you please test [LoggerTests.cs](https://github.com/mariotoffia/FluentDocker/blob/22c07a5c671b445eb4fe960819785c63d5306d6b/Ductus.FluentDocker.Tests/Common/LoggerTests.cs#L42).

If it works properly, you should get the following log statements.
```
Ductus.FluentDocker: message 1
Ductus.FluentDocker: message 2
Ductus.FluentDocker: message 3
```

Btw do you enable logging via 
```cs
Logging.Enabled();
```

Cheers,
 Mario :)

**Comment by gbirchmeier** [comment]
Get anywhere on this?  I'm finding a possibly similar issue.

The error is: `Ductus.FluentDocker.Common.FluentDockerException : Could not dispose composite service from file(s) docker-compose.yaml`

and the top of the stacktrace is just a call to
```
    _compose.Dispose(); // var is a DockerComposeCompositeService
```

It's not much help in diagnosing the problem.

**Comment by codechrysalis-doug** [comment]
> Get anywhere on this? I'm finding a possibly similar issue.
> 
> The error is: `Ductus.FluentDocker.Common.FluentDockerException : Could not dispose composite service from file(s) docker-compose.yaml`
> 
> and the top of the stacktrace is just a call to
> 
> ```
>     _compose.Dispose(); // var is a DockerComposeCompositeService
> ```
> 
> It's not much help in diagnosing the problem.

I made some progress by further debugging into the application level. It seems the errors didn't bubble up in our situation, but we ultimately decided to move away from using this all together in favor of a more cloud native solution.

**Comment by codechrysalis-doug** [comment]
Hi again

> Hi @codechrysalis-doug sorry for late reply. Can you please test [LoggerTests.cs](https://github.com/mariotoffia/FluentDocker/blob/22c07a5c671b445eb4fe960819785c63d5306d6b/Ductus.FluentDocker.Tests/Common/LoggerTests.cs#L42).
> 
> If it works properly, you should get the following log statements.
> 
> ```
> Ductus.FluentDocker: message 1
> Ductus.FluentDocker: message 2
> Ductus.FluentDocker: message 3
> ```
> 
> Btw do you enable logging via
> 
> ```cs
> Logging.Enabled();
> ```
> 
> Cheers, Mario :)

Hi again Mario! it's been 2 years and I had to test this codebase again. Upon trying `Logging.Enabled();`, I wasn't able to find any additional clues. Do you have any other ideas for how I can debug this?

**Comment by mariotoffia** [comment]
**Resolved in v3.0.0.** The v3 ground-up rewrite implements (or fixes) what this issue asked for.

The issue (v2.8.3) is that DockerComposeCompositeService.Dispose() threw a generic, undiagnosable FluentDockerException ("Could not dispose composite service from file(s) ...") that swallowed the real docker error and bubbled up to crash the app; both reporters' core complaint was the total lack of diagnostic detail and the difficulty enabling the old static Serilog logging to see the docker commands. v3 is a ground-up rewrite that resolves all three pain points: (1) the offending class and generic message no longer exist anywhere in the tree; (2) the replacement ComposeService.DisposeCoreAsync() catches teardown failures and LOGS them rather than rethrowing, so a flaky 'compose down' no longer crashes the app; (3) when down genuinely fails (e.g. via RemoveAsync), the thrown DriverException now carries the docker stderr, exit code, stdout and an ErrorContext — exactly the granularity…

<sub>Where this lives in v3: v2 offending code (confirmed via git): commit 858860c Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs line 49 — `throw new FluentDockerException($"Could not dispose composite service {_config.ComposeFilePath}")` rethrown out of Dispose(). v3 replacement: FluentDocker/Services/Impl/ComposeService.cs — Dispose() (lines 281-287) -> DisposeCoreAsync() (lines 297-307) calls RemoveAsync(force:true) inside try/catch and on failure calls `_logger.LogWarning(ex, "ComposeService DisposeAsync failed")` (does NOT rethrow). RemoveAsync (lines 239-264) builds ComposeDownConfig and throws DriverException(message incl. response.Error, response.ErrorCode, response.ErrorContext) on…</sub>

Closing as part of the v3 issue sweep. If your scenario still isn't covered by v3, please reopen with a v3 reproduction and we'll take another look. Thanks for the report! 🙏
