### ISSUE TITLE
GetRunningProcesses extension failed on parsing TimeSpan

### ISSUE THREAD

**Issue by mikhail-khalizev** [mariotoffia/FluentDocker#299]
```
      System.FormatException: String 'Sep08' was not recognized as a valid TimeSpan.
         at System.Globalization.TimeSpanParse.TimeSpanResult.SetBadTimeSpanFailure()
         at System.Globalization.TimeSpanParse.ProcessTerminal_D(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
         at System.Globalization.TimeSpanParse.ProcessTerminalState(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
         at System.Globalization.TimeSpanParse.TryParseTimeSpan(ReadOnlySpan`1 input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
         at System.TimeSpan.Parse(String s)
         at Ductus.FluentDocker.Model.Containers.ProcessRow.ToRow(IList`1 columns, IList`1 fullRow)
         at Ductus.FluentDocker.Executors.Parsers.ClientTopResponseParser.Process(ProcessExecutionResult response)
         at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
         at Ductus.FluentDocker.Commands.Client.Top(DockerUri host, String id, ICertificatePaths certificates)
         at Ductus.FluentDocker.Services.Extensions.ContainerExtensions.GetRunningProcesses(IContainerService service)
```

**Comment by mariotoffia** [comment]
**No longer applicable in v3.0.0.** This was filed against the v2 API, which **no longer exists in v3.0.0** — the ground-up rewrite supersedes it.

The crash was triggered by the v2 `IContainerService.GetRunningProcesses()` extension, which ran `docker top`, fed the output through `ClientTopResponseParser` into `Ductus.FluentDocker.Model.Containers.ProcessRow.ToRow`, and called `TimeSpan.Parse` on the STIME column. STIME is a start timestamp (e.g. `Sep08` for processes older than 24h), never a duration, so it threw FormatException. In v3 that entire entry point is gone: there is no `GetRunningProcesses` extension and no `ClientTopResponseParser`, and `ProcessRow.ToRow`/`Processes` have zero callers in the FluentDocker/ source tree. The new top path (`TopAsync` on the Docker CLI/API and Podman drivers) returns `ContainerProcesses` as raw `List<List<string>>` rows and never parses STIME into a TimeSpan, so the reported crash cannot recur through the public v3 API. NOTE: the buggy `ProcessRow` class was nonetheless carried over…

Closing as part of the v3 issue sweep. If your scenario still isn't covered by v3, please reopen with a v3 reproduction and we'll take another look. Thanks for the report! 🙏
