### ISSUE TITLE
Add podman support

### ISSUE THREAD

**Issue by atrauzzi** [mariotoffia/FluentDocker#300]
Given Dockers decline in reputation over the last while, there's a lot of movement towards podman.

I just tried using this library to run a container on my local podman (linux, Fedora, no Windows!) environment and got the following:

```
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error converting value "" to type 'Ductus.FluentDocker.Model.Containers.HealthState'. Path 'State.Health.Status', line 22, position 32.
 ---> System.ArgumentException: Must specify valid information for parsing in the string.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Ductus.FluentDocker.Executors.Parsers.ClientContainerInspectCommandResponder.Process(ProcessExecutionResult response)
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Commands.Client.InspectContainer(DockerUri host, String id, ICertificatePaths certificates)
   at Ductus.FluentDocker.Services.Impl.DockerHostService.Create(String image, Boolean forcePull, ContainerCreateParams prms, Boolean stopOnDispose, Boolean deleteOnDispose, Boolean deleteVolumeOnDispose, Boolean deleteNamedVolumeOnDispose, String command, String[] args, Func`4 customEndpointResolver)
   at Ductus.FluentDocker.Builders.ContainerBuilder.Build()
```

Anyway, I run containers all the time for local development using jetbrains tooling and CLI.  I have the `docker` and `docker-compose` commands available, mapped to their fully API compatible podman equivalents (if it matters).

**Comment by Rory-Reid** [comment]
I've just tried playing around with podman too and hit the same thing, but I'm not convinced it is FluentDocker's fault.

This failure occurs when parsing the result of `docker inspect`, and it turns out I cannot manually create and `inspect` a single container on my machine and get a valid health state (I'm on macOS if that's useful), they all look like this:

```json
"Health": {
  "Status": "",
  "FailingStreak": 0,
  "Log": null
}
```

FluentDocker is trying to parse `Status` to an enum and not defaulting empty string to unknown, which I guess it could but then the `.WaitForHealthy()` builder function would fail since it looks like it relies on that? I never actually rely on that command it turns out which would work for me but something still feels off.

Not had much luck finding out why this is the case in podman yet, and don't have docker available to compare with just yet.

**Comment by Rory-Reid** [comment]
Definitely more issues once you get past that, failing on the following command:

`docker network ls --no-trunc --format "{{.ID}};{{.Name}};{{.Driver}};{{.Source}};{{.IPv6}};{{.Internal}};{{.CreatedAt}}"`

Several of these properties (eg Source, IPv6, CreatedAt) are not available on either machine I've tested with, and the --format fails very ungracefully when that happens. Within FluentDocker, ID and Name are the only ones currently used, so defensively we could avoid trying to request and parse what we don't need here (though as of now I don't know if this class is public / something you could or would depend on in client code).

Next, it crashes when FluentDocker tries to parse the output of `docker top {container id}`. This is because the TIME column looks something like:
```
TIME
0s
0s
0s
0s
0s
0s
0s
```
And docker's output looks like this:
```
TIME
00:00:00
00:00:04
00:00:00
01:28:20
00:00:00
00:00:12
00:00:00
```
and it cannot parse `0s` to a valid `TimeSpan`

Once again, it looks like this is parsed by FluentDocker but without any internal usage, so could be removed for a more defensive approach to parsing output. It feels a bit rude to go chopping all of this away to support podman here, and ideally podman output would be truly interchangeable with docker output and we'd have none of these issues, but maybe a case could be made for a more generally defensive approach to FluentDocker which would just so happen to solve the immediate problems - remove unused code, and only parse what is strictly needed today?

After making all of these amendments in a local branch, FluentDocker appears to work for me, with podman v4.6.2, within the scope of my limited use in test projects (3 different containers). I'm sure there's a lot more edge cases beyond this.

**Comment by Rory-Reid** [comment]
Have published #303 as a hopefully amicable first-pass support for podman, obviously subject to the maintainer actually wanting to bring this in.

**Comment by mariotoffia** [comment]
Nice work @Rory-Reid - I greatly appreciate it! 

I had one comment, could you please check it out?

Cheers

**Comment by mariotoffia** [comment]
@atrauzzi  sorry, yes, I'll have a look this weekend and make sure to get this going!

**Comment by mariotoffia** [comment]
**Resolved in v3.0.0.** The v3 ground-up rewrite implements (or fixes) what this issue asked for.

This issue is a feature request to add Podman support, with the thread drilling into four specific v2 parsing failures that blocked it: (1) empty Health.Status not defaulting to unknown, (2) Config.Entrypoint failing when emitted as a single string vs array, (3) the brittle `network ls --format "{{.ID}};{{.Name}};..."` template requesting columns Podman doesn't provide, and (4) `docker/podman top` TIME column values like "0s" throwing FormatException on TimeSpan.Parse. v3 ships a complete, first-class Podman CLI driver (PodmanCliDriverPack with 9 component drivers, a WithinPodmanCli() fluent entry, IDriverPack registration via Kernel/PodmanCliDriverBuilder.cs) and every one of the four specific failures is explicitly fixed in code AND covered by dedicated unit tests. There is also an extensive Podman test suite (~30 files). Nothing in the original report still reproduces.

<sub>Where this lives in v3: Driver: FluentDocker/Drivers/Podman/Cli/PodmanCliDriverPack.cs (PodmanCliDriverPack : IDriverPack, 9 component drivers); kernel wiring in FluentDocker/Kernel/PodmanCliDriverBuilder.cs; fluent entry FluentDocker/Builders/Builder.cs WithinPodmanCli() + FluentDocker/Builders/PodmanCliFluentBuilder.cs (incl. UsePod). Specific fixes: (1) Health empty-string -> FluentDocker/Drivers/Podman/Cli/Components/PodmanContainerParser.cs ParseHealth (lines 127-163): if string.IsNullOrEmpty(statusStr) || !Enum.TryParse -> HealthState.Unknown (HealthState enum has Unknown member, FluentDocker/Model/Containers/HealthState.cs). (2) Entrypoint string-or-array -> PodmanContainerParser.ParseStringOrArray (lines…</sub>

Closing as part of the v3 issue sweep. If your scenario still isn't covered by v3, please reopen with a v3 reproduction and we'll take another look. Thanks for the report! 🙏
