### ISSUE TITLE
Machine configuration does not always contain CPU or DiskSize

### ISSUE THREAD

**Issue by perliedman** [mariotoffia/FluentDocker#35]
Related to #33, `Discover` fails for me, since the first returned host (a DigitalOcean host) does not contain `DiskSize` or `CPU` under its `Driver` object, which makes it fail in `MachineInspectResponseParser`:

```
Error Message:
 System.ArgumentNullException : Value cannot be null.
Parameter name: value
Stack Trace:
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Ductus.FluentDocker.Executors.Parsers.MachineInspectResponseParser.Process(ProcessExecutionResult response)
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Commands.Machine.Inspect(String machine)
   at Ductus.FluentDocker.Services.Hosts.<>c.<Discover>b__0_0(MachineLsResponse machine)
   at System.Linq.Enumerable.<>c__DisplayClass151_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Ductus.FluentDocker.Services.Hosts.Discover()
   at Ductus.FluentDocker.Builders.Builder.FindOrDefineHostBuilder()
   at Ductus.FluentDocker.Builders.Builder.UseContainer()
```

If it seems like a good idea to you, I could try making a PR with some more general error handling for missing properties; I don't know enough about the lib to know what the best way to handle missing `DiskSize´ or `CPU` is, though - should we fail (with a better error message), or should this be accepted?

**Comment by mariotoffia** [comment]
@perliedman Please do a PR on this one. You can make it simple since I'd guess the response parsers and model needs a overhaul later on.


Cheers,
 Mario

**Comment by mariotoffia** [comment]
I've done a quick fix in the machine inspect response parser so now you should bee good to go with DigitalOcean. It is release under nugget package version 2.2.3.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@perliedman  I'll close the bug since I've not heard from you.
