### ISSUE TITLE
 System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by bertt** [mariotoffia/FluentDocker#36]
I got a Win32Exception when using FluentDocker 2.2.3 from NuGet in a .NET Core 2.0 console application on Mac with Docker installed.

Code:

```
var hosts = new Hosts().Discover();
```

Error:   System.ComponentModel.Win32Exception, "No such file or directory" on ResolvePath(filename). 

Is this supposed to work on .NET Core?

**Comment by mariotoffia** [comment]
I could be that it cannot find the docker binaries. I currently don't have a mac so I can test this out. Do you have the ability to clone and run one of those Discover tests in a debugger and check if it can find the docker executable?

In meanwhile I need to get a hold on a mac again.
Cheers,
 Mario

**Comment by bertt** [comment]
Running the tests on Mac threw all kind of errors, so I made a small reproducible case see https://github.com/bertt/fluent_docker_win32exception

```
$ git clone https://github.com/bertt/fluent_docker_win32exception
$ cd fluent_docker_win32exception
$ dotnet restore
$ dotnet run
Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Services.Hosts.Discover()
   at fluent_docker_win32exception.Program.Main(String[] args) in /Users/bert/dev/git/bertt/fluent_docker_win32exception/Program.cs:line 10
```

Got the same error when running on Ubuntu with Docker tools installed.

**Comment by mariotoffia** [comment]
@bertt Hi and sorry for not responding sooner. I will check this up this weekend and come back to you.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
@bertt I did a quick check, I think I've found the problem. However can you test to set the ```DOCKER_TOOLBOX_INSTALL_PATH``` to point where the docker binaries are and retry your app.

I'll try to manage to fix the problem this weekend and do a new release.

Cheers, 
 Mario

**Comment by bertt** [comment]
Hi Mario, on Mac the exception disappeared when setting the environment variabele 👍 

```
$ export DOCKER_TOOLBOX_INSTALL_PATH=/usr/local/bin/
```

But now it seems there are no Hosts discovered: new Hosts().Discover() returns 0 hosts but Docker is running.

**Comment by bertt** [comment]
On WSL/Ubuntu I still got Win32 exception:

```
$ export DOCKER_TOOLBOX_INSTALL_PATH=/usr/local/bin/
$ dotnet run

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStd
out, Boolean redirectStderr, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Services.Hosts.Discover()
   at fluent_docker_win32exception.Program.Main(String[] args) in /mnt/d/dev/github.com/bertt/fluent_docker_win32exception/Program.cs:line
 10
```

**Comment by mariotoffia** [comment]
@bertt I've rewritten the part of searching for docker binaries and probing for "native" docker daemons. I've tested it on windows and (see below) on linux. Can you have a try? Please update the nugget reference to 2.2.5.

Cheers, 
 Mario

```
using Ductus.FluentDocker.Builders;
using Ductus.FluentDocker.Extensions;
using Ductus.FluentDocker.Model.Builders;
using Ductus.FluentDocker.Model.Common;
using Ductus.FluentDocker.Model.Containers;
using Ductus.FluentDocker.Services;
using Ductus.FluentDocker.Services.Extensions;
using System;

namespace Tests
{
    class Program
    {
        static void Main(string[] args)
        {
            var hosts = new Hosts().Discover();
            Console.WriteLine($"Number of hosts:{hosts.Count}");
            foreach(var host in hosts)
            {
                Console.WriteLine($"{host.Host} {host.Name} {host.State}");
            }
            Console.WriteLine("Spinning up a postgres and wait for ready state...");
            using (
                var container =
                new Builder().UseContainer()
                    .UseImage("postgres:9.6-alpine")
                    .ExposePort(5432)
                    .WithEnvironment("POSTGRES_PASSWORD=mysecretpassword")
                    .WaitForPort("5432/tcp", 30000 /*30s*/)
                    .Build()
                    .Start())
            {
                var config = container.GetConfiguration(true);
                if (ServiceRunningState.Running == config.State.ToServiceState())
                {
                    Console.WriteLine("Service is running");
                }
                else
                {
                    Console.WriteLine("Failed to start nginx instance...");
                }
            }  
        }
    }
}
```

**Comment by mariotoffia** [comment]
@bertt Today I borrowed a collegues mac and verified the above functionality and it did pick up the instance. Unless you had any problems in regards of listing docker-machine related rather than the "EmulatedNative" I'm going to close this issue soon.

Cheers,
 Mario

**Comment by bertt** [comment]
Hi Mario, tried it on Ubuntu/WSL (without setting the DOCKER_TOOLBOX_INSTALL_PATH var) but now got another error at 'dotnet run':

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Ductus.FluentDocker.Extensions.CommandExtensions' threw an exception. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ductus.FluentDocker.Extensions.Utils.DockerBinariesResolver..ctor(String[] paths)
   at Ductus.FluentDocker.Extensions.CommandExtensions..cctor()
   --- End of inner exception stack trace ---
   at Ductus.FluentDocker.Commands.Machine.Ls()
   at Ductus.FluentDocker.Services.Hosts.Discover()
   at fluent_docker_win32exception.Program.Main(String[] args) in /mnt/d/dev/github.com/bertt/fluent_docker_win32exception/Program.cs:line 10
```

**Comment by mariotoffia** [comment]
@bertt  Haven't tried on wsl - will do it this weekend and make sure it works there as well. You are using the docker client as elf binaries or do you use it via the windows binaries?

**Comment by bertt** [comment]
basically it runs like this: http://blog.bigfont.ca/run-docker-from-the-wsl/
i'll try on mac tonight.

**Comment by bertt** [comment]
on mac it runs now allright 👍

**Comment by mariotoffia** [comment]
@bertt I've updated the package to 2.2.7 and run your test. I've modified to output the paths discovered to docker, docker-compose and docker-machine. I'm running in WSL and have the windows _paths_ prepended - the standard behavior on WSL (thus windows docker binaries discovered first). My output for the test is:
```
docker        : C:\Program Files\Docker\Docker\Resources\bin\docker.exe
docker-compose: C:\Program Files\Docker\Docker\Resources\bin\docker-compose.exe
docker-machine: C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe
Number of hosts:2
 test-machine Stopped
npipe:////./pipe/docker_engine native Running
Spinning up a postgres and wait for ready state...
Service is running
```

And the test code is:
```csharp
namespace Tests
{
    class Program
    {
        static void Main(string[] args)
        {
            var r = new DockerBinariesResolver();
            Console.WriteLine("docker        : " + (r.MainDockerClient.FqPath ?? "not found"));
            Console.WriteLine("docker-compose: " + (r.MainDockerCompose.FqPath ?? "not found"));
            Console.WriteLine("docker-machine: " + (r.MainDockerMachine.FqPath ?? "not found"));

            var hosts = new Hosts().Discover();
            Console.WriteLine($"Number of hosts:{hosts.Count}");
            foreach(var host in hosts)
            {
                Console.WriteLine($"{host.Host} {host.Name} {host.State}");
            }
            Console.WriteLine("Spinning up a postgres and wait for ready state...");
            using (
                var container =
                new Builder().UseContainer()
                    .UseImage("postgres:9.6-alpine")
                    .ExposePort(5432)
                    .WithEnvironment("POSTGRES_PASSWORD=mysecretpassword")
                    .WaitForPort("5432/tcp", 30000 /*30s*/)
                    .Build()
                    .Start())
            {
                var config = container.GetConfiguration(true);
                if (ServiceRunningState.Running == config.State.ToServiceState())
                {
                    Console.WriteLine("Service is running");
                }
                else
                {
                    Console.WriteLine("Failed to start postgres instance...");
                }
            }
        }
    }
}
```

If this solves your problem, please notify me so I can close this issue.

Cheers,
 Mario

**Comment by bertt** [comment]
mac, windows works allright. but still got an error in WSL on Discover method:

```
docker        : /usr/bin/docker
docker-compose: /usr/bin/docker-compose

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ductus.FluentDocker.Commands.Machine.Ls()
   at Ductus.FluentDocker.Services.Hosts.Discover()
   at fluent_docker_win32exception.Program.Main(String[] args) in /mnt/d/dev/github.com/bertt/fluent_docker_win32exception/Program.cs:line 17
```

and r.MainDockerMachine also gives NullReferenceException

Shall I try it on an Ubuntu machine instead of WSL?

**Comment by mariotoffia** [comment]
@bertt Where do you have docker-machine executable? It seems that it cannot find it on your path.

**Comment by bertt** [comment]
on WSL there is no docker-machine installed, its only on the windows site. But I guess Hosts().Discover() should be able to run.

**Comment by mariotoffia** [comment]
@bertt Have a go - I've emulated your setup in test case and now it works. Update to version _2.2.8_ and it should be fine.

Cheers,
 Mario

**Comment by bertt** [comment]
yup working now on all platforms 👍 thanks for the assistance,
