### ISSUE TITLE
.NET Core 2.0 Compatibility Issue

### ISSUE THREAD

**Issue by rkttu-devsisters** [mariotoffia/FluentDocker#37]
One problem I found when I installed and tested the nuget package in the .NET Core 2.0 MSTest project. When I run the code like below, runtime throws 'MissingMethodException'.

```
new Builder().UseContainer()
            .UseImage("mysql-server:5.7")
...
;
```

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
  Source=Ductus.FluentDocker
  StackTrace:
   at Ductus.FluentDocker.Common.Logger.<>c.<.cctor>b__2_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Ductus.FluentDocker.Common.Logger.Log(String message)
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Services.Hosts.Discover()
   at Ductus.FluentDocker.Builders.Builder.FindOrDefineHostBuilder()
   at Ductus.FluentDocker.Builders.Builder.UseContainer()
...
   at Ductus.FluentDocker.MsTest.FluentDockerTestBase.Initialize()
```

The exception says that the runtime can not find the extension method ServiceCollectionContainerBuilderExtensions.BuildServiceProvider that returns an instance of type IServiceProvider.

In fact, in .NET Core 2.0, Microsoft has created a breaking change with a version of the method that returns the ServiceProvider class instead of the IServiceProvider interface, and it seems that a MissingMethodException is being thrown.

It seems to be possible to use this library in a .NET Core 2.0 project only by fixing this problem.

**Comment by mariotoffia** [comment]
Thanks for reporting! I'll have a look tomorrow and fix the issue.

Cheers,
 Mario

**Comment by mariotoffia** [comment]
The project now contains dependencies on 1.1 and 2.0 simultaneously and is verified to work with a test app using _netcoreapp2.0_.
